### ISSUE TITLE
Implement two factor authentication

### ISSUE THREAD

**Issue by ingdicath** [ingdicath/transcendence#59]
As a user, I want to have the option to enable two-factor authentication for added security when logging into my account.

**Acceptance Criteria:**

 - The user should be able to enable _two-factor authentication_ in their account settings.
- The user should be able to choose _Google Authenticator_ method of two-factor authentication. 
- When two-factor authentication is enabled, the user must be prompted to enter a verification code after entering their username and password.
- The verification code must be valid for a limited time and expire if not used.
- If the user enters an incorrect verification code, they must be given the option to retry.
- The user must be notified if there are any attempts to log into their account without the two-factor authentication code.

**Comment by TessavdL** [comment]
implemented on #95
